version: "3.5"

services:
  app:
    build: .
    # entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    entrypoint: ./.docker/entrypoint.sh
    container_name: api-2
    ports:
      - 3002:3000
    volumes:
      - .:/home/node/app
    networks:
      # - app-network
      - rabbit-ms_network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  # app-network:
  #   driver: bridge
  rabbit-ms_network:
    external: true
